<?php

declare(strict_types=1);

namespace igorbunov\Checkbox\Mappers;

use igorbunov\Checkbox\Mappers\Receipts\Taxes\GoodTaxesMapper;
use PHPUnit\Framework\TestCase;

class GetAllTaxesTest extends TestCase
{
    /** @var  string $jsonString */
    private $jsonString;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->jsonString = '[
           {
              "id":"17578582-0c4b-472a-8d78-610496d41c8c",
              "code":1234567891,
              "label":"Побори",
              "symbol":"Я",
              "rate":12,
              "extra_rate":15,
              "included":true,
              "created_at":"2020-10-22T15:37:09+00:00",
              "updated_at":"2020-10-22T15:42:36+00:00"
           },
           {
              "id":"0ec9f407-81bc-4302-9a23-75f644e5f1cc",
              "code":1234567890,
              "label":"ПДВ",
              "symbol":"A",
              "rate":5,
              "extra_rate":null,
              "included":true,
              "created_at":"2020-10-07T11:22:07+00:00",
              "updated_at":"2020-10-07T11:22:07+00:00"
           },
           {
              "id":"8a18b9d2-2ecf-4979-9aef-655553b4c644",
              "code":123123,
              "label":"4",
              "symbol":"Д",
              "rate":5,
              "extra_rate":null,
              "included":true,
              "created_at":"2020-08-14T13:32:07+00:00",
              "updated_at":"2020-10-22T16:14:11+00:00"
           },
           {
              "id":"32ec7945-3aa4-4132-88e2-ba14cceed0ea",
              "code":4,
              "label":"ПДВ",
              "symbol":"В",
              "rate":7,
              "extra_rate":0,
              "included":true,
              "created_at":"2020-08-17T10:03:12+00:00",
              "updated_at":"2020-10-26T10:53:33+00:00"
           },
           {
              "id":"4929433d-ba43-4b22-972a-4c76df80491c",
              "code":2,
              "label":"Акцизний збір",
              "symbol":"Г",
              "rate":0,
              "extra_rate":5,
              "included":true,
              "created_at":"2020-08-22T19:49:12+00:00",
              "updated_at":"2020-10-26T10:53:41+00:00"
           },
           {
              "id":"a7fcc45a-af65-46fb-8762-a76a09623991",
              "code":3,
              "label":"Без ПДВ",
              "symbol":"Е",
              "rate":0,
              "extra_rate":0,
              "included":true,
              "created_at":"2020-08-17T10:06:31+00:00",
              "updated_at":"2020-10-26T10:54:08+00:00"
           },
           {
              "id":"afbe8511-460f-4d99-ae87-f46ba96154a8",
              "code":1,
              "label":"ПДВ А",
              "symbol":"Є",
              "rate":20,
              "extra_rate":0,
              "included":true,
              "created_at":"2020-08-22T19:48:42+00:00",
              "updated_at":"2020-10-26T10:54:18+00:00"
           },
           {
              "id":"cace2c2a-6477-4416-8f70-040b6c2f139c",
              "code":5,
              "label":"Не є об\'єктом оподаткування",
              "symbol":"И",
              "rate":0,
              "extra_rate":0,
              "included":true,
              "created_at":"2020-08-17T09:41:16+00:00",
              "updated_at":"2020-10-26T10:54:47+00:00"
           },
           {
              "id":"2908951d-92a9-4bf4-8f9e-79a4f6c82393",
              "code":1230321,
              "label":"Без ПДВ",
              "symbol":"Б",
              "rate":0,
              "extra_rate":3,
              "included":true,
              "created_at":"2020-10-02T12:46:10+00:00",
              "updated_at":"2020-10-08T16:22:21+00:00"
           },
           {
              "id":"b147e4b3-f19b-4baf-a279-0391249cf5af",
              "code":123124,
              "label":"1",
              "symbol":"Ж",
              "rate":1,
              "extra_rate":1,
              "included":true,
              "created_at":"2020-08-17T12:01:18+00:00",
              "updated_at":"2020-10-08T16:24:47+00:00"
           },
           {
              "id":"ba428fb4-d8d3-442b-851b-0e028218c69c",
              "code":33333,
              "label":"2",
              "symbol":"З",
              "rate":1,
              "extra_rate":6,
              "included":true,
              "created_at":"2020-08-14T13:34:49+00:00",
              "updated_at":"2020-10-08T16:25:03+00:00"
           }
        ]';
    }

    public function testMapShiftWithNull(): void
    {
        $this->assertNull(
            (new GoodTaxesMapper())->jsonToObject(null)
        );
    }

    public function testMapGetShiftWithJson(): void
    {
        $jsonResponse = json_decode($this->jsonString, true);

        $mapped = (new GoodTaxesMapper())->jsonToObject($jsonResponse);

        $this->assertEquals(
            '17578582-0c4b-472a-8d78-610496d41c8c',
            $mapped->results[0]->id
        );
        $this->assertEquals(
            '0ec9f407-81bc-4302-9a23-75f644e5f1cc',
            $mapped->results[1]->id
        );
    }
}
