<?php

namespace Mappers\Receipts;

use igorbunov\Checkbox\Mappers\Receipts\PrepaymentReceiptMapper;
use igorbunov\Checkbox\Models\Receipts\Delivery;
use igorbunov\Checkbox\Models\Receipts\Goods\GoodItemModel;
use igorbunov\Checkbox\Models\Receipts\Goods\GoodModel;
use igorbunov\Checkbox\Models\Receipts\Goods\Goods;
use igorbunov\Checkbox\Models\Receipts\Payments\CashPaymentPayload;
use igorbunov\Checkbox\Models\Receipts\Payments\Payments;
use igorbunov\Checkbox\Models\Receipts\PrepaymentReceipt;
use PHPUnit\Framework\TestCase;

use function json_decode;

class PrepaymentReceiptMapperTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stu
    }


    public function testObjectToJson(): void
    {
        $expected = '{
            "cashier_name":"\u0412\u0430\u0441\u044f \u041f\u0443\u043f\u043a\u0456\u043d",
            "departament":"\u0412\u0456\u0434\u0434\u0456\u043b \u043f\u0440\u043e\u0434\u0430\u0436\u0456\u0432",
            "goods":[
                {"good":{
                    "code":"vm-123",
                    "name":"\u0411\u0438\u043e\u0432\u0430\u043a",
                    "barcode":"",
                    "header":"",
                    "footer":"",
                    "price":100,
                    "tax":[],
                    "uktzed":""
                },
                "quantity":1000,
                "is_return":false,
                "discounts":[]
                }
            ],
            "delivery":{
            "emails":["test@mail.com"]
            },
            "discounts":[],
            "payments":[
            {"type":"CASH","value":"10","label":"\u0413\u043e\u0442\u0456\u0432\u043a\u043e\u044e"}
            ],
            "header":"",
            "footer":"",
            "barcode":""
        }';
        $receipt = new PrepaymentReceipt(
            'Вася Пупкін',
            'Відділ продажів',
            new Goods(
                [
                    new GoodItemModel(
                        new GoodModel('vm-123', 100, 'Биовак'),
                        1000
                    )
                ]
            ),
            new Delivery(["test@mail.com"]),
            new Payments(
                [
                    new CashPaymentPayload(10)
                ]
            )
        );

        $prepaymentReceiptObject = (new PrepaymentReceiptMapper())->objectToJson($receipt);
        self::assertEquals(
            json_decode($expected, true),
            $prepaymentReceiptObject
        );
    }
}
